services:
  mc-test:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: "PAPER"
    ports:
      - "25565:25565"
      - "19132:19132/udp"
    volumes:
      - ./server:/data
      - ./build/libs/TelemetryPlugin-dev.jar:/data/plugins/TelemetryPlugin-dev.jar