name: Telemetry
version: 1.1.0
main: art.chibi.telemetry.TelemetryPlugin
bootstrapper: art.chibi.telemetry.Bootstrap
description: Sends telemetry data.
author: dondelay
website: https://chibi.art
api-version: '1.21.4'